# Author: @FarDust -> Gabriel Andres Faundez Soto
version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_NAME: postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres